export default {
  UPDATE_LOCAL_BOARD_SLOT: 'UPDATE_LOCAL_BOARD_SLOT',
  UPDATE_LOCAL_BOARD_TURN: 'UPDATE_LOCAL_BOARD_TURN',
  RESET_LOCAL_BOARD: 'RESET_LOCAL_BOARD',
  DIMISS_WINNER_POPUP: 'DIMISS_WINNER_POPUP',
  UPDATE_CONNECTION_STATUS: 'UPDATE_CONNECTION_STATUS',
  UPDATE_STATE_KEY: 'UPDATE_STATE_KEY',
  UPDATE_CHAT: 'UPDATE_CHAT',
  UPDATE_ONLINE_BOARD: 'UPDATE_ONLINE_BOARD',
  JOIN_ROOM: 'JOIN_ROOM',
  DIMISS_ONLINE_WINNER_POPUP: 'DIMISS_ONLINE_WINNER_POPUP',
  UPDATE_GAME_END: 'UPDATE_GAME_END',
}
